const data = [{"id": 0,"name": "Remera Basic Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 1,"name": "Remera Basic White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 3,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 4,"name": "Remera Strenght White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]}, {"id": 5,"name": "Remera Basic Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 6,"name": "Remera Basic White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 7,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 8,"name": "Remera Strenght White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},{"id": 9,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 11,"name": "Remera Basic White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 13,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 14,"name": "Remera Strenght White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]}, {"id": 15,"name": "Remera Basic Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 16,"name": "Remera Basic White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 17,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},
{"id": 18,"name": "Remera Strenght White", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/bmm33017_white_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},{"id": 19,"name": "Remera Strength Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]},{"id": 10,"name": "Remera Basic Black", "precio": 7500, "talles":["M","L","XL"], "imagenes": ["https://media.boohoo.com/i/boohoo/mzz44826_black_xl/?qlt=80&fmt=auto","https://media.boohoo.com/i/boohoo/mzz44826_black_xl_1/herren-schwarz-basic-oversized-t-shirt-mit-tasche"]}]

export default data;    